---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: le-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-nvidia-open
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  # - type: dnf
  #   # repos:
  #   #   copr:
  #   #     - atim/starship # Adds COPR repository for Starship
  #   install:
  #     packages:
  #       #- micro # Terminal text editor (modern alternative to nano)
  #       #- starship # Fancy shell prompt customization
  #   remove:
  #     packages:
  #       # example: removing firefox (in favor of the flatpak)
  #       # "firefox" is the main package, "firefox-langpacks" is a dependency
  #       # - firefox
  #       # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          # - org.mozilla.firefox
          - io.missioncenter.MissionCenter        # System monitor (Task Manager alternative, shows CPU/RAM/GPU usage)
          - org.fedoraproject.MediaWriter         # Create bootable USB drives from ISOs
          - org.gnome.Loupe                       # GNOME image viewer (minimal, fast)
          - org.gnome.DejaDup                     # Backup tool (simple backup/restore for your files)
          - org.kde.haruna                        # Video player based on MPV (lightweight, powerful)
          - org.kde.kcalc                         # KDE calculator
          - org.kde.kclock                        # KDE clock/timer/stopwatch app
          - org.kde.okular                        # PDF/document viewer (feature-rich, annotations, forms)
          - com.github.tchx84.Flatseal            # Manage Flatpak permissions (control app sandboxing)
          - com.ranfdev.DistroShelf               # Browse and install apps from various sources
          - io.github.flattool.Warehouse          # Manage Flatpaks (alternative to GNOME Software for Flatpaks)
          - io.podman_desktop.PodmanDesktop       # Container management GUI (Docker alternative)
          - io.github.getnf.embellish             # Nerd Fonts installer/manager (programming fonts with icons)
          - me.iepure.devtoolbox                  # Developer utilities collection (JSON formatter, regex tester, etc.)

      - scope: user # Also add Flathub user repo, but no user packages
  - type: rpm-ostree
    repos:
      - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
    optfix:
      - brave.com
    keys:
      - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    install:
      - brave-browser

  - type: bling
    install:
      - 1password

  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry

  - type: fonts
    fonts:
    nerd-fonts:
      - FiraCode # don't add spaces or "Nerd Font" suffix
      - Hack
      - SourceCodePro
      - Terminus
      - JetBrainsMono
      - NerdFontsSymbolsOnly
    google-fonts:
      - Roboto
      - Open Sans

  # - type: chezmoi
  #   repository: "https://github.com/octocat/dotfiles" # my dotfiles repo
  #   all-users: false # make users have to enable chezmoi manually
  #   file-conflict-policy: replace # override changed files with those from the repo


  - type: signing # this sets up the proper policy & signing files for signed images to work fully
